config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('liberty.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liberty/urls.py
from django.urls import path

from liberty.views import AuthorView, CreateView, DetailsView, ExploreView, UserLoginview, UserRegisterView, filter_items, home_page, item_updateView

app_name = "liberty"

urlpatterns = [
    path('', home_page, name="home"),
    path('explore/', ExploreView.as_view(), name="explore"),
    path('details/<int:pk>', DetailsView.as_view(), name="details"),
    path('author/', AuthorView.as_view(), name="author"),
    path('create/', CreateView.as_view(), name='create' ),    
    path('login/', UserLoginview.as_view(), name = 'login' ),    
    path('register/', UserRegisterView.as_view(), name = 'register'),
    path('update/<int:pk>', item_updateView, name = 'update'),
      path('filter/', filter_items, name='filter_products'),
]

liberty/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

from liberty.utils import avatar_path, image_path

    
# Create your models here.
class Author(models.Model):
    username = models.CharField(max_length= 28)
    first_name = models.CharField(max_length = 128)
    last_name = models.CharField(max_length = 128)
    avatar = models.ImageField(upload_to= avatar_path, default ='avatar.jpg' )
    like_count = models.IntegerField(default=0)

    def str(self) -> str:
        return self.first_name


class Item(models.Model):
    image = models.ImageField(upload_to=image_path, default ='Image.jpg')
    title = models.CharField(max_length = 128)
    author = models.ForeignKey(Author, on_delete = models.CASCADE, related_name = 'items' )
    body = models.TextField()
    bid = models.FloatField()
    owner = models.CharField(max_length = 28)
    owner_username = models.CharField(max_length = 28)
    ends_in = models.TimeField()
    category =  models.ForeignKey("Category", on_delete = models.CASCADE, related_name='items')

class Category(models.Model):
    name = models.CharField(max_length=128,  null=False, blank=False)

    def __str__(self) -> str:
        return self.name

liberty/forms.py
from django import forms
from django.forms import ModelForm, ImageField, Form, CharField, PasswordInput
from .models import Author, Item
from .models import User

class UserRegisterForm(forms.ModelForm):
    avatar = ImageField()
    password = CharField(max_length = 128, widget=PasswordInput)

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data["password"])
        user.save()
        return user

    class Meta:
        model = User
        fields = ("avatar", "username", "first_name", "last_name")

class UserLoginForm(Form):
    username = CharField(max_length=128)
    password = CharField(max_length=128, widget=PasswordInput)

class ItemCreateForm(forms.ModelForm):
    image = ImageField()
    class Meta:
        model= Item
        fields = "__all__"

class ItemUpdateForm(forms.ModelForm):
    image = ImageField()
    class Meta:
        model = Item
        fields = "__all__"

# class AuthorRegisterForm(forms.ModelForm):
#     avatar = ImageField()
#     password = CharField(max_length = 128, widget=PasswordInput)

#     # def save(self, commit=True):
#     #     user = super().save(commit)
#     #     user.set_password(self.cleaned_data["password"])
#     #     user.save()
#     #     return user

#     class Meta:
#         model = Author
#         fields = ("avatar", "username", "first_name", "last_name")




# class AuthorLoginForm(Form):
#     username = CharField(max_length=128)
#     password = CharField(max_length=128, widget=PasswordInput)

liberty/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from liberty.forms import ItemCreateForm, ItemUpdateForm, UserLoginForm, UserRegisterForm


from liberty.models import Category, Item, Author

class ExploreView(View):
    def get(self, request):
        items = Item.objects.all()
        authors = Author.objects.all()
        categories = Category.objects.all()
        return render(request, 'explore.html', context={"items":items, "authors":authors, "categories":categories})
    
    
class DetailsView(View):
    def get(self, request, pk):
        items = Item.objects.all()
        authors = Author.objects.all()
        return render(request, 'details.html', context={"items":items, "authors":authors})
    
class AuthorView(View):
    def get(self, request):
        authors = Author.objects.all()
        items = Item.objects.all()
        return render(request, 'author.html', {'authors': authors, "items":items})
    

def home_page(request):
    items = Item.objects.all().order_by("ends_in")
    size = request.GET.get("size", 2)
    page = request.GET.get("page", 1)
    paginator = Paginator(items, size)
    page_obj = paginator.page(page)
    context = {
        "items": page_obj.object_list, 
        "page_obj": page_obj, 
        "num_pages": paginator.num_pages
    }
    return render(request, "index.html", context=context)


class UserRegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        return render (request, "register.html", {'form': form})
    
    def post (self, request):
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Sucessfully registered")
            return redirect("liberty:login")
        else:
            return render(request, "register.html", {'form':form})

class UserLoginview(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, "login.html", {'form': form})
    
    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request, user)
                messages.success(request, f"you have logged in as {username}")
                return redirect ('liberty:create')
            else:
                messages.erorr(request, "Wrong username or password")
                return render(request, "login.html", {"form": form})
        else:
            return render(request, "login.html", {"form": form})

class UserLogout(View):
    def get(self, request):
        logout(request)
        messages.success(request, "user successfully logged out!")
        return redirect ('liberty:home')
    
class CreateView(View):
    def get(self, request):
        form = ItemCreateForm() 
        return render(request, 'create.html', {'form' : form})
    
    def post(self, request):
       form = ItemCreateForm(request.POST, request.FILES)
       if form.is_valid():
            item = form.save(commit=False)
            
            item.save()
            return redirect ('liberty:home')
       else:
           return render (request, 'create.html', {'form' : form})
       
def item_updateView(request, pk: int):
    item = Item.objects.get(pk=pk)
    if request.method == "POST":
        form = ItemUpdateForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, "post successfully updated")
            return redirect('liberty:details', pk=pk)
    else:
        form = ItemUpdateForm(instance=item)
    return render(request, "update.html", {"form": form, "item":item})

def filter_items(request):
    keyword = request.POST.get('keyword')
    category = request.POST.get('category')

    items = Item.objects.all()

    if keyword:
        items = items.filter(title=keyword)

    if category:
        items = items.filter(category=category)

    return render(request, 'filtered_items.html', {'products': items})

liberty/templates/author.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

  <div class="page-heading normal-space">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Author Details</h6>
          <h2>View Details For Author</h2>
          <span>Home > <a href="#">Author</a></span>
          <div class="buttons">
            <div class="main-button">
              <a href="e{% url 'liberty:explore' %}">Explore Our Items</a>
            </div>
            <div class="border-button">
              <a href="{% url 'liberty:create' %}">Create Your NFT</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% for author in authors %}
  <div class="author-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="author">
            <img src="{{author.avatar.url}}" alt="" style="border-radius: 50%; max-width: 170px;">
            <h4>{{author.first_name}} {{author.last_name}}<br> <a href="#"></a>{{author.username}}</h4>
          </div>
        </div>
        
        <div class="col-lg-6">
          <div class="right-info">
            <div class="row">
              <div class="col-4">
                <div class="info-item">
                  <i class="fa fa-heart"></i>
                  <h6>{{author.like_count}} <em>Likes</em></h6>
                </div>
              </div>
              <div class="col-4">
                <div class="info-item">
                  <i class="fa fa-hand"></i>
                  <h6>{{author.like_count}} <em>Likes</em></h6>
                </div>
              </div>
              <div class="col-4">
                <div class="info-item">
                  <i class="fa fa-dollar"></i>
                  <h6>{{author.like_count}} <em>Likes</em></h6>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-5">
                <h5>559 Followers</h5>
              </div>
              <div class="col-7">
                <div class="main-button">
                  <a href="#">Follow {{author.username}}</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        

        <div class="col-lg-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>Samandar’s <em>Items</em>.</h2>
          </div>
        </div>
        {% for author in authors %}
        {% for item in items %}
        <div class="col-lg-3 col-md-6">
          <div class="item">
            <div class="row">
              <div class="col-lg-12">
                <span class="author">
                  <img src="{{ author.avatar.url }}" alt="" style="max-width: 50px; border-radius: 50%;">
                </span>
                <img src="{{ item.image.url }}" alt="" style="border-radius: 20px;">
                <h4>{{item.title}}</h4>
              </div>
              <div class="col-lg-12">
                <div class="line-dec"></div>
                <div class="row">
                  <div class="col-6">
                    <span>Current Bid: <br> <strong>{{ item.current_bid }}</strong></span>
                  </div>
                  <div class="col-6">
                    <span>Ends In: <br> <strong>{{item.ends_in}}</strong></span>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="main-button">
                  <a href="{% url 'liberty:details' item.pk %}">View Details</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endfor %}
        
      </div>
    </div>
  </div>
  {% endfor %}

  <div class="create-nft">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>Create Your NFT & Put It On The Market.</h2>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="main-button">
            <a href="{% url 'liberty:create' %}">Create Your NFT Now</a>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item first-item">
            <div class="number">
              <h6>1</h6>
            </div>
            <div class="icon">
              <img src="{% static 'assets/images/icon-02.png' %}" alt="">
            </div>
            <h4>Set Up Your Wallet</h4>
            <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item second-item">
            <div class="number">
              <h6>2</h6>
            </div>
            <div class="icon">
              <img src="{% static 'assets/images/icon-04.png' %}" alt="">
            </div>
            <h4>Add Your Digital NFT</h4>
            <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item">
            <div class="icon">
              <img src="{% static 'assets/images/icon-06.png' %}" alt="">
            </div>
            <h4>Sell Your NFT &amp; Make Profit</h4>
            <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

liberty/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

    <title>Liberty NFT - Author Detail Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-liberty-market.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet"href="{% static 'https://unpkg.com/swiper@7/swiper-bundle.min.css' %}"/>
<!--


TemplateMo 577 Liberty Market

https://templatemo.com/tm-577-liberty-market

-->
  </head>
  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
      <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </div>
    <!-- ***** Preloader End ***** -->
  
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
    
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <nav class="main-nav">
                      <!-- ***** Logo Start ***** -->
                      <a href="index.html" class="logo">
                          <img src="assets/images/logo.png" alt="">
                      </a>
                      <!-- ***** Logo End ***** -->
                      <!-- ***** Menu Start ***** -->
                      
                      <ul class="nav">
                          <li><a href="{% url 'liberty:home' %}">Home</a></li>
                          <li><a href="{% url 'liberty:explore' %}">Explore</a></li>
                          
                          <li><a href="{% url 'liberty:author' %}">Author</a></li>
                          <li><a href="{% url 'liberty:create' %}" class="active">Create Yours</a></li>
                      </ul>   
                      <a class='menu-trigger'>
                          <span>Menu</span>
                      </a>
                      <!-- ***** Menu End ***** -->
                  </nav>
              </div>
          </div>
      </div>
      
    </header>
    <!-- ***** Header Area End ***** -->

   {% block body %}

   {% endblock %}

 <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2022 <a href="#">Liberty</a> NFT Marketplace Co., Ltd. All rights reserved.
          &nbsp;&nbsp;
          Designed by <a title="HTML CSS Templates" rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>
<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/isotope.min.js' %}"></script>
<script src="{% static 'assets/js/owl-carousel.js' %}"></script>

<script src="{% static 'assets/js/tabs.js' %}"></script>
<script src="{% static 'assets/js/popup.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
  </body>
</html>

liberty/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

  <div class="page-heading normal-space">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Liberty NFT Market</h6>
          <h2>View Item Details</h2>
          <span>Home > <a href="#">Item Details</a></span>
          <div class="buttons">
            <div class="main-button">
              <a href="{% url 'liberty:explore' %}">Explore Our Items</a>
            </div>
            <div class="border-button">
              <a href="{% url 'liberty:create' %}">Create Your NFT</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% for item in items%}
  <div class="item-details-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>View Details <em>For Item</em> Here.</h2>
          </div>
        </div>
        <div class="col-lg-7">
          <div class="left-image">
            
            <img src="{{item.image.url}}" alt="" style="border-radius: 20px;">
          </div>
          
        </div>
        
        <div class="col-lg-5 align-self-center">
          <h4>{{items.title}}</h4>
          <span class="author">
            <img src="{{item.image.url}}" alt="" style="max-width: 50px; border-radius: 50%;">
            <h6>{{item.author.first_name}} {{item.author.last_name}}<br><a href="#">{{item.author.username}}</a></h6>
          </span>
          <p>{{item.body}}</p>
          <div class="row">
            <div class="col-3">
              <span class="bid">
                Current Bid<br><strong>{{item.bid}} ETH</strong><br><em>(${{item.bid}})</em>
              </span>
            </div>
            <div class="col-4">
              <span class="owner">
                Owner<br><strong>{{item.owner}}</strong><br><em>({{item.owner_nickname}})</em>
              </span>
            </div>
            <div class="col-5">
              <span class="ends">
                Ends In<br><strong>{{item.ends_in}}</strong><br><em>(January 22nd, 2021)</em>
              </span>
            </div>
          </div>
          <form action="submit">
            <label for="quantity-text">Place Bid:</label>
            <input placeholder="1 ETH" class="quantity-text">
            <button type="submit" id="form-submit" class="main-button">Submit Now</button>
            
          </form>
          <h3>Update product</h3>
          <h3><a href="{% url 'liberty:update' pk=item.pk %}" class="main-button">Update</a></h3>
        </div>
        
        <div class="col-lg-12">
          <div class="current-bid">
            <div class="row">
              <div class="col-lg-6">
                <div class="mini-heading"><h4>Current Biddings Prices ( ETH )</h4></div>
              </div>
              <div class="col-lg-6">
                <fieldset>
                  <select name="Category" class="form-select" aria-label="Default select example" id="chooseCategory" onchange="this.form.click()">
                      <option selected>Sort By: Latest</option>
                      <option type="checkbox" name="option1" value="old">Sort By: Oldest</option>
                      <option value="low">Sort By: Lowest</option>
                      <option value="high">Sort By: Highest</option>
                  </select>
              </fieldset>
              </div>
              {% for item in items %}
              {% for author in authors %}
              <div class="col-lg-4 col-md-6">
                <div class="item">
                  <div class="left-img">
                    <img src="{{author.avatar.url}}" alt="">
                  </div>
                  <div class="right-content">
                    <h4>{{author.first_name}} {{author.last_name}}</h4>
                    <a href="#">{{author.nickname}}</a>
                    <div class="line-dec"></div>
                    <h6>Bid: <em>0.06 ETH</em></h6>
                    <span class="date">24/07/2022, 22:00</span>
                  </div>
                </div>
              </div>
              {% endfor %}
              {% endfor %}
              

              <!-- <div class="col-lg-4 col-md-6">
                <div class="item">
                  <div class="left-img">
                    <img src="{% static 'assets/images/current-02.jpg' %}" alt="">
                  </div>
                  <div class="right-content">
                    <h4>David Walker</h4>
                    <a href="#">@davidwalker</a>
                    <div class="line-dec"></div>
                    <h6>Bid: <em>0.06 ETH</em></h6>
                    <span class="date">24/07/2022, 22:00</span>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <div class="item">
                  <div class="left-img">
                    <img src="{% static 'assets/images/current-03.jpg' %}" alt="">
                  </div>
                  <div class="right-content">
                    <h4>David Walker</h4>
                    <a href="#">@davidwalker</a>
                    <div class="line-dec"></div>
                    <h6>Bid: <em>0.06 ETH</em></h6>
                    <span class="date">24/07/2022, 22:00</span>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <div class="item">
                  <div class="left-img">
                    <img src="{% static 'assets/images/current-02.jpg' %}" alt="">
                  </div>
                  <div class="right-content">
                    <h4>David Walker</h4>
                    <a href="#">@davidwalker</a>
                    <div class="line-dec"></div>
                    <h6>Bid: <em>0.06 ETH</em></h6>
                    <span class="date">24/07/2022, 22:00</span>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <div class="item">
                  <div class="left-img">
                    <img src="{% static 'assets/images/current-04.jpg' %}" alt="">
                  </div>
                  <div class="right-content">
                    <h4>David Walker</h4>
                    <a href="#">@davidwalker</a>
                    <div class="line-dec"></div>
                    <h6>Bid: <em>0.06 ETH</em></h6>
                    <span class="date">24/07/2022, 22:00</span>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-6">
                <div class="item">
                  <div class="left-img">
                    <img src="{% static 'assets/images/current-01.jpg' %}" alt="">
                  </div>
                  <div class="right-content">
                    <h4>David Walker</h4>
                    <a href="#">@davidwalker</a>
                    <div class="line-dec"></div>
                    <h6>Bid: <em>0.06 ETH</em></h6>
                    <span class="date">24/07/2022, 22:00</span>
                  </div>
                </div>
              </div> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <div class="create-nft">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>Create Your NFT & Put It On The Market.</h2>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="main-button">
            <a href="{% url 'liberty:create' %}">Create Your NFT Now</a>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item first-item">
            <div class="number">
              <h6>1</h6>
            </div>
            <div class="icon">
              <img src="{% static 'assets/images/icon-02.png' %}" alt="">
            </div>
            <h4>Set Up Your Wallet</h4>
            <p>There are 5 different HTML pages included in this NFT <a href="https://templatemo.com/page/1" target="_blank" rel="nofollow">website template</a>. You can edit or modify any section on any page as you required.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item second-item">
            <div class="number">
              <h6>2</h6>
            </div>
            <div class="icon">
              <img src="{% static 'assets/images/icon-04.png' %}" alt="">
            </div>
            <h4>Add Your Digital NFT</h4>
            <p>If you would like to support our TemplateMo website, please visit <a rel="nofollow" href="https://templatemo.com/contact" target="_parent">our contact page</a> to make a PayPal contribution. Thank you.</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item">
            <div class="icon">
              <img src="{% static 'assets/images/icon-06.png' %}" alt="">
            </div>
            <h4>Sell Your NFT &amp; Make Profit</h4>
            <p>NFT means Non-Fungible Token that are used in digital cryptocurrency markets. There are many different kinds of NFTs in the industry.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

liberty/templates/filtered_items.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h2>Filtered Products</h2>
    <div class="row">
        {% if items %}
            {% for item in items %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card">
                        <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.title }}</h5>
                            <p class="card-text">{{ item.body }}</p>
                            <p class="card-text"><small class="text-muted">Category: {{ item.category }}</small></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col">
                <p>No items found.</p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

liberty/templates/login.html
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h3>Login Page</h3>
            <form action="{% url 'liberty:login' %}"  method = "post">
                {% csrf_token %}
                {{ form | crispy}}
                <button type="submit">Submit</button>
            </form>
        <p>If you dont have an account, please pass through <a href="{% url 'liberty:register' %}">Registration</a></p>
    </div>
        </div>
</div>
{% endblock %}

liberty/templates/pagination.html
<div class="row">


    <div class="col-6">
        {% if  page_obj.has_previous %}

            <a href="{% url 'liberty:home' %}?page=1">first</a>
            <a href="{% url 'liberty:home' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
        {{ page_obj.number }}
        {% if  page_obj.has_next %}
            <a href="{% url 'liberty:home' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            <a href="{% url 'liberty:home' %}?page={{ num_pages }}">last</a>
        {% endif %}

        {#         <a href="{% url 'liberty:home' %}?size={{ page_obj.next_page_number }}""></a></p>#}

    </div>
    <div class="col-3">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                    aria-expanded="false">
                Page Size
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'liberty:home' %}?size=5">5</a>
                <a class="dropdown-item" href="{% url 'liberty:home' %}?size=10">10</a>
                <a class="dropdown-item" href="{% url 'liberty:home' %}?size=20">20</a>
            </div>
        </div>
    </div>

</div>

liberty/templates/register.html
{% load crispy_forms_tags %}
{% block body %}
    <h3>Register Page</h3>
    <form method = post enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy}}
        <button type="submit">Submit</button>
    </form>


{% endblock %}

liberty/templates/update.html
<h3>Update product</h3>
    <form method="post" enctype="multipart/form-data" action="{% url 'liberty:update' pk=item.pk %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-5">
          
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Update</button>
       </div>
    </div>
</form>